
package Swing;

import Pojo.Pesanan;
import Interface.PesananInterface;
import Controller.PesananController;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ramzi
 */
public class PesananSwing extends javax.swing.JFrame {

    /**
     * Creates new form PesananSwing
     */
    
    PesananInterface pesananInterface;
    
    public PesananSwing() {
       initComponents();
       this.setLocationRelativeTo(null);
        loadData();
        getKodeProduk();
        getUsernamePembeli();
        btn_qris.setEnabled(false);
    }

    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    
     private void loadData() {
        pesananInterface = new PesananController();
        List<Pesanan> listPesanan = new ArrayList<>();
        listPesanan = pesananInterface.findAll();
        Object[][] objectPesanan = new Object[listPesanan.size()][4];
        
        int counter = 0;
        for (Pesanan pesanan : listPesanan) {
            objectPesanan[counter][0] = pesanan.getId_pesanan();
            objectPesanan[counter][1] = pesanan.getUsername_pembeli();
            objectPesanan[counter][2] = pesanan.getKode_Produk();
            objectPesanan[counter][3] = pesanan.getJumlah_pesanan();
            
            cb_kode_produk.addItem(pesanan.getKode_Produk());
            cb_username_pembeli.addItem(pesanan.getUsername_pembeli());
            counter++;
        }
        
        tabel_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            objectPesanan,
            new String [] {
                "ID Pesanan", "Username Pembeli", "Kode Produk", "Jumlah Pesanan"
            }
        ));
        
    }
   
    private void getKodeProduk(){
        pesananInterface = new PesananController();
        List<Pesanan> listPesanan = new ArrayList<>();
        listPesanan = pesananInterface.findKodeProd();
        cb_kode_produk.removeAllItems();
        
        for (Pesanan pesanan : listPesanan) {
            cb_kode_produk.addItem(pesanan.getKode_Produk());
        }
        
    }
    
     private void getUsernamePembeli(){
        pesananInterface = new PesananController();
        List<Pesanan> listPesanan = new ArrayList<>();
        listPesanan = pesananInterface.findUserPem();
        cb_username_pembeli.removeAllItems();
        
        for (Pesanan pesanan : listPesanan) {
            cb_username_pembeli.addItem(pesanan.getUsername_pembeli());
        }
    }
      
    private void loadData(Pesanan pesanan) {
        Object[][] objectPesanan= new Object[1][8];
        
            objectPesanan[0][0] = pesanan.getId_pesanan();
            objectPesanan[0][1] = pesanan.getUsername_pembeli();
            objectPesanan[0][2] = pesanan.getKode_Produk();
            objectPesanan[0][3] = pesanan.getJumlah_pesanan();
            
         tabel_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            objectPesanan,
            new String [] {
                "ID Pesanan", "Username Pembeli", "Kode Produk", "Jumlah Pesanan"
            }
        ));
    }
    
    private Pesanan findPesanan(Integer id) {

        Pesanan pesanan = new Pesanan();
        pesananInterface = new PesananController();
        pesanan =  pesananInterface.findById(id);
    
        return pesanan;
    }
    
    public void emptyField (){
        txt_id_pesanan.setText("");
        txt_jumlah_pesanan.setText("");
    }
    
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pesanan = new javax.swing.JTable();
        txt_search_id = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txt_id_pesanan = new javax.swing.JTextField();
        txt_jumlah_pesanan = new javax.swing.JTextField();
        btn_search_id = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cb_username_pembeli = new javax.swing.JComboBox<>();
        cb_kode_produk = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_qris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pesanan", "Username Pembeli", "Kode Product", "Jumlah Pesanan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 600, 270));

        txt_search_id.setText("Search");
        txt_search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 330, 30));

        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 30));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 30));

        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 30));

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 30));

        txt_id_pesanan.setText("ID_Pesanan");
        getContentPane().add(txt_id_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 30));

        txt_jumlah_pesanan.setText("Jumlah Pesanan");
        getContentPane().add(txt_jumlah_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 30));

        btn_search_id.setText("Search");
        btn_search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_idActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, 30));

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 30));

        jLabel1.setText("Jumlah Pesanan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cb_username_pembeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb_username_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 270, 30));

        cb_kode_produk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb_kode_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 270, 30));

        jLabel2.setText("Username Pembeli");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel3.setText("ID Pesanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setText("Kode Produk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        btn_qris.setText("Lihat QRIS");
        btn_qris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qrisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_qris, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_idActionPerformed

    }//GEN-LAST:event_txt_search_idActionPerformed

    private void tabel_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pesananMouseClicked
        String id_pesanan, username_pembeli, kode_produk;
        int jumlah_pesanan;
        pesananInterface = new PesananController();
        
        int row = tabel_pesanan.getSelectedRow();
        id_pesanan = tabel_pesanan.getValueAt(row, 0).toString();
        username_pembeli = tabel_pesanan.getValueAt(row, 1).toString();
        kode_produk = tabel_pesanan.getValueAt(row, 2).toString();
        jumlah_pesanan = Integer.parseInt(tabel_pesanan.getValueAt(row, 3).toString());
        
        int activatedQris = pesananInterface.userPayment(kode_produk);
        
        if (activatedQris == 1) {
            btn_qris.setEnabled(true);
        } else {
            btn_qris.setEnabled(false);
        }
        
    }//GEN-LAST:event_tabel_pesananMouseClicked

    private void btn_search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_idActionPerformed
    int id;
        Pesanan searchedPesanan = new Pesanan();
        
        id = Integer.parseInt(txt_search_id.getText());
        searchedPesanan = findPesanan(id);
        if (searchedPesanan != null) {
            loadData(searchedPesanan);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }


    }//GEN-LAST:event_btn_search_idActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        int id_pesanan;
        int row = tabel_pesanan.getSelectedRow();
        pesananInterface = new PesananController();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        id_pesanan = Integer.parseInt(tabel_pesanan.getValueAt(row, 0).toString());
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure to delete it?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            pesananInterface.delete(id_pesanan);
            loadData();
       
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        loadData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        int id_pesanan;
        String username_pembeli, kode_produk;
        int jumlah_pesanan;

        pesananInterface = new PesananController();
        id_pesanan= Integer.parseInt(txt_id_pesanan.getText());
        username_pembeli = cb_username_pembeli.getSelectedItem().toString();
        kode_produk = cb_kode_produk.getSelectedItem().toString();
        jumlah_pesanan = Integer.parseInt(txt_jumlah_pesanan.getText());

        Pesanan pesanan = new Pesanan();
        pesanan.setId_pesanan(id_pesanan);
        pesanan.setUsername_pembeli(username_pembeli);
        pesanan.setKode_Produk(kode_produk);
        pesanan.setJumlah_pesanan(jumlah_pesanan);

        pesananInterface.create(pesanan);
        JOptionPane.showMessageDialog(null, "Data pesanan created successfully");
        loadData();
        emptyField();
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int id_pesanan;
        String username_pembeli, kode_produk;
        int jumlah_pesanan;
        pesananInterface = new PesananController();

        id_pesanan = Integer.parseInt(txt_id_pesanan.getText());
        username_pembeli = cb_username_pembeli.getSelectedItem().toString();
        kode_produk = cb_kode_produk.getSelectedItem().toString();
        jumlah_pesanan = Integer.parseInt(txt_jumlah_pesanan.getText());

        Pesanan pesanan = new Pesanan();
        pesanan.setId_pesanan(id_pesanan);
        pesanan.setUsername_pembeli(username_pembeli);
        pesanan.setKode_Produk(kode_produk);
        pesanan.setJumlah_pesanan(jumlah_pesanan);

        pesananInterface.update(pesanan);
        JOptionPane.showMessageDialog(null, "Data pesanan Updated successfully");
        loadData();
        emptyField();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_qrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qrisActionPerformed
        try {
            String id_pesanan, username_pembeli, kode_produk;
            int jumlah_pesanan;
            pesananInterface = new PesananController();

            int row = tabel_pesanan.getSelectedRow();
            id_pesanan = tabel_pesanan.getValueAt(row, 0).toString();
            username_pembeli = tabel_pesanan.getValueAt(row, 1).toString();
            kode_produk = tabel_pesanan.getValueAt(row, 2).toString();
            jumlah_pesanan = Integer.parseInt(tabel_pesanan.getValueAt(row, 3).toString());
            
            String QrCodeData= "{\n"
                    + "    'id_pesanan':"+id_pesanan+",\n"
                    + "    'username_pembeli':"+username_pembeli+",\n"
                    + "    'kode_produk':"+kode_produk+",\n"
                    + "    'jumlah_pesanan':"+jumlah_pesanan+",\n"
                    + "}";
            
            String filePath= "C:\\Users\\alzildan\\Documents\\Kuliah\\SEMESTER 3\\ISB-205 P - OOP\\tugas akhir\\Qr.png";
            String charset= "UTF-8";
            Map <EncodeHintType,ErrorCorrectionLevel> hintMap= new HashMap <EncodeHintType,ErrorCorrectionLevel> ();
            hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            BitMatrix  matrix= new MultiFormatWriter().encode(
            new String (QrCodeData.getBytes(charset),charset),
            BarcodeFormat.QR_CODE,200,200,hintMap);

            MatrixToImageWriter.writeToFile(matrix, filePath.substring(filePath.lastIndexOf('.')+1),new File(filePath));

            ImageIcon icon = new ImageIcon(filePath);
            JFrame frame = new JFrame();
            JLabel label = new JLabel(icon);
            frame.add(label);
            frame.setDefaultCloseOperation
                (JFrame.DISPOSE_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btn_qrisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesananSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesananSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesananSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesananSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesananSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_qris;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search_id;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_kode_produk;
    private javax.swing.JComboBox<String> cb_username_pembeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pesanan;
    private javax.swing.JTextField txt_id_pesanan;
    private javax.swing.JTextField txt_jumlah_pesanan;
    private javax.swing.JTextField txt_search_id;
    // End of variables declaration//GEN-END:variables
}
